name: explorify
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  url_launcher: ^6.0.17
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5
  sqflite: ^2.0.0+3
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  connectivity_plus: ^2.2.0
  internet_connection_checker: ^0.0.1+3
  overlay_support: ^1.2.1
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0
  battery_plus: ^2.1.0
  local_auth: ^1.1.10
  flutter_jailbreak_detection: ^1.8.0
  flutter_windowmanager: ^0.2.0
  device_info_plus: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/pics/

